# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86b88c6439b48217cde0350307e1f7977709de900e4e4f69ae1393fd62553932f660cd153fd34220cbb28f297d2bb4a7de02d65acb1160e82b6b1c616f5360ab

test:
  secret_key_base: 09a62bb0d5b6fb0f36c05580221936a845feb71c0690cd0151b567b282c673894b2a2f9c532a33d3d40b0bd5910d65979cc1b24c211630c7179eb16f7435b172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
